require:
  - standard
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - public/**/*
    - vendor/**/*
    - db/schema.rb

Rails:
  Enabled: true

Minitest:
  Enabled: true

Performance:
  Enabled: true
